/**
 * Seed data for the watch_references table.
 * 20 popular watches spanning diverse categories, origins, and price points.
 *
 * The first 9 are from the user's existing collection + wishlist.
 * The remaining 11 round out the catalog for diversity.
 */

export type WatchSeedEntry = {
  slug: string;
  brand: string;
  model: string;
  reference: string;
  sizeMm: number;
  movement: string;
  material: string;
  color: string;
  category: string;
  braceletType: string;
  shape: string;
  waterResistanceM: number;
  crystal: string;
  caseBack: string;
  origin: string;
  lugWidthMm: number;
  complications: string[];
  retailPrice: number;
  description: string;
  imageUrl: string | null;
};

export const SEED_WATCHES: WatchSeedEntry[] = [
  // -----------------------------------------------------------------------
  // 1-9: User's existing collection + wishlist
  // -----------------------------------------------------------------------
  {
    slug: "rolex-submariner-date-126610ln",
    brand: "Rolex",
    model: "Submariner Date",
    reference: "126610LN",
    sizeMm: 41,
    movement: "automatic",
    material: "stainless steel",
    color: "black",
    category: "diver",
    braceletType: "steel bracelet",
    shape: "round",
    waterResistanceM: 300,
    crystal: "sapphire",
    caseBack: "solid",
    origin: "Swiss",
    lugWidthMm: 21,
    complications: ["date"],
    retailPrice: 10250,
    description:
      "The quintessential dive watch. Ceramic bezel, Oystersteel case, Calibre 3235.",
    imageUrl: null,
  },
  {
    slug: "hamilton-khaki-pilot-day-date-h64615135",
    brand: "Hamilton",
    model: "Khaki Pilot Day Date",
    reference: "H64615135",
    sizeMm: 42,
    movement: "automatic",
    material: "stainless steel",
    color: "black",
    category: "pilot",
    braceletType: "steel bracelet",
    shape: "round",
    waterResistanceM: 100,
    crystal: "sapphire",
    caseBack: "display",
    origin: "Swiss",
    lugWidthMm: 20,
    complications: ["day", "date"],
    retailPrice: 1135,
    description:
      "Bold aviation-inspired dial with day and date windows. H-40 movement with 80-hour power reserve.",
    imageUrl: null,
  },
  {
    slug: "seiko-prospex-alpinist-spb121",
    brand: "Seiko",
    model: "Prospex Alpinist",
    reference: "SPB121",
    sizeMm: 39.5,
    movement: "automatic",
    material: "stainless steel",
    color: "green",
    category: "field",
    braceletType: "leather strap",
    shape: "round",
    waterResistanceM: 200,
    crystal: "sapphire",
    caseBack: "solid",
    origin: "Japanese",
    lugWidthMm: 20,
    complications: ["date", "compass"],
    retailPrice: 599,
    description:
      "Heritage alpinist with sunburst green dial and inner compass ring. 6R35 movement.",
    imageUrl: null,
  },
  {
    slug: "casio-vintage-multiface-a130weg-9a",
    brand: "Casio",
    model: "Vintage Multiface",
    reference: "A130WEG-9A",
    sizeMm: 40.5,
    movement: "battery",
    material: "stainless steel",
    color: "gold",
    category: "digital",
    braceletType: "steel bracelet",
    shape: "rectangular",
    waterResistanceM: 30,
    crystal: "mineral",
    caseBack: "solid",
    origin: "Japanese",
    lugWidthMm: 18,
    complications: ["alarm", "stopwatch", "countdown timer"],
    retailPrice: 92,
    description:
      "Retro gold-tone digital with multi-function display. Everyday beater with vintage charm.",
    imageUrl: null,
  },
  {
    slug: "omega-speedmaster-moonwatch-310-30-42-50-01-001",
    brand: "Omega",
    model: "Speedmaster Moonwatch",
    reference: "310.30.42.50.01.001",
    sizeMm: 42,
    movement: "manual wind",
    material: "stainless steel",
    color: "black",
    category: "chronograph",
    braceletType: "steel bracelet",
    shape: "round",
    waterResistanceM: 50,
    crystal: "hesalite",
    caseBack: "solid",
    origin: "Swiss",
    lugWidthMm: 20,
    complications: ["chronograph", "tachymeter"],
    retailPrice: 6550,
    description:
      "The Moonwatch. Calibre 3861 manual-wind, hesalite crystal, step dial. Flight-qualified by NASA.",
    imageUrl: null,
  },
  {
    slug: "tudor-black-bay-58-m79030n-0001",
    brand: "Tudor",
    model: "Black Bay 58",
    reference: "M79030N-0001",
    sizeMm: 39,
    movement: "automatic",
    material: "stainless steel",
    color: "black",
    category: "diver",
    braceletType: "steel bracelet",
    shape: "round",
    waterResistanceM: 200,
    crystal: "sapphire",
    caseBack: "solid",
    origin: "Swiss",
    lugWidthMm: 20,
    complications: [],
    retailPrice: 3575,
    description:
      "Vintage-sized diver with gilt accents. MT5402 COSC-certified movement, 70-hour power reserve.",
    imageUrl: null,
  },
  {
    slug: "grand-seiko-shunbun-sbga413",
    brand: "Grand Seiko",
    model: "Shunbun",
    reference: "SBGA413",
    sizeMm: 40,
    movement: "automatic",
    material: "stainless steel",
    color: "white",
    category: "dress",
    braceletType: "leather strap",
    shape: "round",
    waterResistanceM: 100,
    crystal: "sapphire",
    caseBack: "display",
    origin: "Japanese",
    lugWidthMm: 19,
    complications: ["date", "power reserve indicator"],
    retailPrice: 6300,
    description:
      "Spring Drive with pink-tinted snowflake dial inspired by cherry blossoms. Zaratsu-polished case.",
    imageUrl: null,
  },
  {
    slug: "nomos-tangente-2date-135",
    brand: "Nomos",
    model: "Tangente 2date",
    reference: "135",
    sizeMm: 37.5,
    movement: "automatic",
    material: "stainless steel",
    color: "white",
    category: "dress",
    braceletType: "leather strap",
    shape: "round",
    waterResistanceM: 30,
    crystal: "sapphire",
    caseBack: "display",
    origin: "German",
    lugWidthMm: 18,
    complications: ["date"],
    retailPrice: 2780,
    description:
      "Bauhaus minimalism with Glashutte finishing. DUW 6101 in-house movement.",
    imageUrl: null,
  },
  {
    slug: "oris-pointer-date-4365-07",
    brand: "Oris",
    model: "Pointer Date",
    reference: "4365-07",
    sizeMm: 40,
    movement: "automatic",
    material: "stainless steel",
    color: "blue",
    category: "field",
    braceletType: "leather strap",
    shape: "round",
    waterResistanceM: 50,
    crystal: "sapphire",
    caseBack: "display",
    origin: "Swiss",
    lugWidthMm: 20,
    complications: ["pointer date"],
    retailPrice: 2400,
    description:
      "Classic Oris pointer date complication on a blue dial. Clean, versatile everyday watch.",
    imageUrl: null,
  },

  // -----------------------------------------------------------------------
  // 10-20: Additional popular watches for catalog diversity
  // -----------------------------------------------------------------------
  {
    slug: "omega-seamaster-diver-300m-210-30-42-20-03-001",
    brand: "Omega",
    model: "Seamaster Diver 300M",
    reference: "210.30.42.20.03.001",
    sizeMm: 42,
    movement: "automatic",
    material: "stainless steel",
    color: "blue",
    category: "diver",
    braceletType: "steel bracelet",
    shape: "round",
    waterResistanceM: 300,
    crystal: "sapphire",
    caseBack: "display",
    origin: "Swiss",
    lugWidthMm: 20,
    complications: ["date"],
    retailPrice: 5500,
    description:
      "Laser-engraved wave dial, ceramic bezel, Co-Axial 8800 movement.",
    imageUrl: null,
  },
  {
    slug: "citizen-promaster-diver-bn0151-09l",
    brand: "Citizen",
    model: "Promaster Diver",
    reference: "BN0151-09L",
    sizeMm: 42,
    movement: "solar",
    material: "stainless steel",
    color: "blue",
    category: "diver",
    braceletType: "rubber strap",
    shape: "round",
    waterResistanceM: 200,
    crystal: "mineral",
    caseBack: "solid",
    origin: "Japanese",
    lugWidthMm: 20,
    complications: ["date"],
    retailPrice: 230,
    description:
      "Eco-Drive solar-powered diver. ISO 6425 certified. No battery changes ever.",
    imageUrl: null,
  },
  {
    slug: "g-shock-casioak-ga2100-1a1",
    brand: "Casio",
    model: "G-Shock CasiOak",
    reference: "GA2100-1A1",
    sizeMm: 45.4,
    movement: "quartz",
    material: "resin",
    color: "black",
    category: "digital",
    braceletType: "resin strap",
    shape: "round",
    waterResistanceM: 200,
    crystal: "mineral",
    caseBack: "solid",
    origin: "Japanese",
    lugWidthMm: 22,
    complications: ["stopwatch", "alarm", "world time"],
    retailPrice: 110,
    description:
      "Octagonal bezel inspired by the AP Royal Oak. Carbon Core Guard structure, analog-digital.",
    imageUrl: null,
  },
  {
    slug: "tissot-prx-powermatic-80-t137-407-11-041-00",
    brand: "Tissot",
    model: "PRX Powermatic 80",
    reference: "T137.407.11.041.00",
    sizeMm: 40,
    movement: "automatic",
    material: "stainless steel",
    color: "blue",
    category: "dress",
    braceletType: "steel bracelet",
    shape: "round",
    waterResistanceM: 100,
    crystal: "sapphire",
    caseBack: "display",
    origin: "Swiss",
    lugWidthMm: 20,
    complications: ["date"],
    retailPrice: 695,
    description:
      "Integrated bracelet sports-luxury. 80-hour power reserve. Incredible value proposition.",
    imageUrl: null,
  },
  {
    slug: "sinn-556-i-b",
    brand: "Sinn",
    model: "556 I B",
    reference: "556.010",
    sizeMm: 38.5,
    movement: "automatic",
    material: "stainless steel",
    color: "black",
    category: "field",
    braceletType: "steel bracelet",
    shape: "round",
    waterResistanceM: 200,
    crystal: "sapphire",
    caseBack: "solid",
    origin: "German",
    lugWidthMm: 20,
    complications: ["date"],
    retailPrice: 1490,
    description:
      "No-nonsense German tool watch. Sellita SW200-1, anti-magnetic, perfectly legible.",
    imageUrl: null,
  },
  {
    slug: "cartier-tank-must-wsta0065",
    brand: "Cartier",
    model: "Tank Must",
    reference: "WSTA0065",
    sizeMm: 33.7,
    movement: "quartz",
    material: "stainless steel",
    color: "white",
    category: "dress",
    braceletType: "leather strap",
    shape: "rectangular",
    waterResistanceM: 30,
    crystal: "sapphire",
    caseBack: "solid",
    origin: "Swiss",
    lugWidthMm: 18,
    complications: [],
    retailPrice: 3100,
    description:
      "Iconic rectangular case since 1917. Roman numeral dial, blued sword hands, cabochon crown.",
    imageUrl: null,
  },
  {
    slug: "seiko-5-sports-srpd55",
    brand: "Seiko",
    model: "5 Sports",
    reference: "SRPD55",
    sizeMm: 42.5,
    movement: "automatic",
    material: "stainless steel",
    color: "blue",
    category: "diver",
    braceletType: "nato strap",
    shape: "round",
    waterResistanceM: 100,
    crystal: "mineral",
    caseBack: "display",
    origin: "Japanese",
    lugWidthMm: 22,
    complications: ["day", "date"],
    retailPrice: 275,
    description:
      "Affordable automatic diver-style with day-date. 4R36 movement, exhibition caseback.",
    imageUrl: null,
  },
  {
    slug: "junghans-max-bill-027-3501-04",
    brand: "Junghans",
    model: "Max Bill Automatic",
    reference: "027/3501.04",
    sizeMm: 38,
    movement: "automatic",
    material: "stainless steel",
    color: "white",
    category: "dress",
    braceletType: "leather strap",
    shape: "round",
    waterResistanceM: 30,
    crystal: "acrylic",
    caseBack: "solid",
    origin: "German",
    lugWidthMm: 20,
    complications: ["date"],
    retailPrice: 1150,
    description:
      "Bauhaus icon designed by Max Bill. Domed acrylic crystal, J800.1 automatic movement.",
    imageUrl: null,
  },
  {
    slug: "orient-bambino-v2-fac00005w0",
    brand: "Orient",
    model: "Bambino V2",
    reference: "FAC00005W0",
    sizeMm: 40.5,
    movement: "automatic",
    material: "stainless steel",
    color: "white",
    category: "dress",
    braceletType: "leather strap",
    shape: "round",
    waterResistanceM: 30,
    crystal: "mineral",
    caseBack: "solid",
    origin: "Japanese",
    lugWidthMm: 21,
    complications: [],
    retailPrice: 130,
    description:
      "Domed dial and crystal give a vintage feel. In-house caliber F6724, incredible value for a dress automatic.",
    imageUrl: null,
  },
  {
    slug: "marathon-gsar-ww194006",
    brand: "Marathon",
    model: "GSAR",
    reference: "WW194006",
    sizeMm: 41,
    movement: "automatic",
    material: "stainless steel",
    color: "black",
    category: "diver",
    braceletType: "rubber strap",
    shape: "round",
    waterResistanceM: 300,
    crystal: "sapphire",
    caseBack: "solid",
    origin: "Swiss",
    lugWidthMm: 20,
    complications: ["date"],
    retailPrice: 1200,
    description:
      "Military-spec dive watch with tritium lume. US Government dial markings, ETA 2824-2.",
    imageUrl: null,
  },
];
